FROM epahomov/docker-spark:spark_2.1_hadoop_2.6


COPY /anaconda/Anaconda2-4.3.1-Linux-x86_64.sh /anaconda/anaconda.sh


# anaconda copy
RUN bash /anaconda/anaconda.sh -b -p /opt/anaconda

RUN rm -r -f /spark/metastored_b



