version: '2'
services:
 
  cuny-code:
    image: foodproof_cuny-code
    volumes:
      - ./source:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - db
      
  myadmin:
   image: phpmyadmin/phpmyadmin
   ports:
     - "8080:80"
   depends_on:
      - db

  db:
    image: mysql/mysql-server
    environment:
      MYSQL_USER: newuser
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: foodproof_users
      MYSQL_ROOT_HOST: 172.17.0.1
    volumes:
        - ./db_scripts:/docker-entrypoint-initdb.d
  